// export.js — generate Cookie Clicker mod JS from form state

function gv(id) {
  const el = document.getElementById(id);
  if (!el) return null;
  if (el.type === "checkbox") return el.checked;
  const v = el.value.trim();
  return v === "" ? null : v;
}

function num(id, def = 1) {
  const v = parseFloat(gv(id));
  return isNaN(v) ? def : v;
}

function safeName(str) {
  return (str || "unnamed")
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/^[0-9]/, "_$&");
}

function generateMod() {
  const modName    = gv("mod-name")    || "My Mod";
  const modId      = gv("mod-id")      || "my-mod";
  const modVersion = gv("mod-version") || "1.0.0";
  const modAuthor  = gv("mod-author")  || "";
  const modDesc    = gv("mod-desc")    || "";

  const cursorCps   = num("cursor-cps", 1);
  const cursorClick = num("cursor-click", 1);

  const buildingMults = getBuildingMultipliers();

  const gcFreq     = num("gc-freq", 1);
  const gcDuration = num("gc-duration", 1);
  const gcReward   = num("gc-reward", 1);
  const gcFrenzy   = num("gc-frenzy", 1);

  const globalCps        = num("global-cps", 1);
  const startingCookies  = num("starting-cookies", 0);
  const disableWrinklers = gv("toggle-wrinklers");
  const lockSeason       = gv("toggle-seasons");
  const customJs         = gv("custom-js") || "";

  const upgrades = getUpgrades();
  const blabs    = getBlabs();

  const lines = [];

  lines.push(`// ${modName} v${modVersion}`);
  if (modAuthor) lines.push(`// by ${modAuthor}`);
  if (modDesc)   lines.push(`// ${modDesc}`);
  lines.push(`// Generated by CCMM (Cookie Clicker Mod Builder)`);
  lines.push(``);
  lines.push(`Game.registerMod("${modId}", {`);
  lines.push(`  id: "${modId}",`);
  lines.push(`  name: "${modName.replace(/"/g, '\\"')}",`);
  lines.push(`  version: "${modVersion}",`);
  lines.push(``);
  lines.push(`  init: function() {`);
  lines.push(``);

  // ---- cursor multipliers ----
  if (cursorCps !== 1 || cursorClick !== 1) {
    lines.push(`    // Cursor multipliers`);
    if (cursorCps !== 1) {
      lines.push(`    Game.registerHook("cps", function() {`);
      lines.push(`      var cursor = Game.Objects["Cursor"];`);
      lines.push(`      if (cursor) cursor.storedCps *= ${cursorCps};`);
      lines.push(`    });`);
    }
    if (cursorClick !== 1) {
      lines.push(`    var _origMouseCps = Game.computedMouseCps;`);
      lines.push(`    Game.computedMouseCps = function() {`);
      lines.push(`      return _origMouseCps.call(this) * ${cursorClick};`);
      lines.push(`    };`);
    }
    lines.push(``);
  }

  // ---- building multipliers ----
  const nonDefaultBuildings = Object.entries(buildingMults).filter(([, v]) => v !== 1);
  if (nonDefaultBuildings.length > 0) {
    lines.push(`    // Building CPS multipliers`);
    lines.push(`    Game.registerHook("cps", function() {`);

    const buildingNameMap = {
      cursor: "Cursor", grandma: "Grandma", farm: "Farm", mine: "Mine",
      factory: "Factory", bank: "Bank", temple: "Temple",
      wizardtower: "Wizard Tower", shipment: "Shipment",
      alchemylab: "Alchemy Lab", portal: "Portal",
      timemachine: "Time Machine", antimatter: "Antimatter Condenser",
      prism: "Prism", chancemaker: "Chancemaker",
      fractal: "Fractal Engine", javascript: "Javascript Console",
      idleverse: "Idleverse", cortex: "Cortex Baker",
    };

    nonDefaultBuildings.forEach(([id, mult]) => {
      const name = buildingNameMap[id] || id;
      lines.push(`      if (Game.Objects["${name}"]) Game.Objects["${name}"].storedCps *= ${mult};`);
    });

    lines.push(`    });`);
    lines.push(``);
  }

  // ---- golden cookie tweaks ----
  const gcChanged = gcFreq !== 1 || gcDuration !== 1 || gcReward !== 1 || gcFrenzy !== 1;
  if (gcChanged) {
    lines.push(`    // Golden cookie tweaks`);

    if (gcFreq !== 1) {
      lines.push(`    var _origGCmaxTime = Game.shimmer.prototype.maxTime;`);
      lines.push(`    // Frequency multiplier: lower value = appears more often`);
      lines.push(`    Game.registerHook("logic", function() {`);
      lines.push(`      for (var i in Game.shimmers) {`);
      lines.push(`        var s = Game.shimmers[i];`);
      lines.push(`        if (s.type === "golden") {`);
      lines.push(`          s.maxTime = s.maxTime * ${gcFreq};`);
      lines.push(`        }`);
      lines.push(`      }`);
      lines.push(`    });`);
    }

    if (gcDuration !== 1) {
      lines.push(`    var _origDie = Game.shimmer.prototype.pop;`);
      lines.push(`    Game.shimmer.prototype.lifeTime = (Game.shimmer.prototype.lifeTime || 13) * ${gcDuration};`);
    }

    if (gcReward !== 1) {
      lines.push(`    var _origReward = Game.goldenCookie.prototype ? Game.goldenCookie.prototype.getEffect : null;`);
      lines.push(`    var _origEarn = Game.Earn;`);
      lines.push(`    Game.Earn = function(n) {`);
      lines.push(`      return _origEarn.call(this, n);`);
      lines.push(`    };`);
      lines.push(`    Game.goldenCookieRewardMult = ${gcReward};`);
    }

    if (gcFrenzy !== 1) {
      lines.push(`    // Frenzy duration multiplier`);
      lines.push(`    if (Game.buffs["Frenzy"]) {`);
      lines.push(`      Game.buffs["Frenzy"].time *= ${gcFrenzy};`);
      lines.push(`    }`);
    }

    lines.push(``);
  }

  // ---- global CPS ----
  if (globalCps !== 1) {
    lines.push(`    // Global CPS multiplier`);
    lines.push(`    Game.registerHook("cps", function() {`);
    lines.push(`      Game.cookiesPs *= ${globalCps};`);
    lines.push(`    });`);
    lines.push(``);
  }

  // ---- starting cookies ----
  if (startingCookies > 0) {
    lines.push(`    // Starting cookies`);
    lines.push(`    if (Game.cookies < ${startingCookies}) {`);
    lines.push(`      Game.cookies = ${startingCookies};`);
    lines.push(`    }`);
    lines.push(``);
  }

  // ---- disable wrinklers ----
  if (disableWrinklers) {
    lines.push(`    // Disable wrinklers`);
    lines.push(`    Game.registerHook("logic", function() {`);
    lines.push(`      for (var i in Game.wrinklers) {`);
    lines.push(`        Game.wrinklers[i].type = 1;`);
    lines.push(`        Game.wrinklers[i].phase = 0;`);
    lines.push(`      }`);
    lines.push(`    });`);
    lines.push(``);
  }

  // ---- lock season ----
  if (lockSeason) {
    lines.push(`    // Lock season to none`);
    lines.push(`    Game.season = "";`);
    lines.push(`    Game.seasonT = 0;`);
    lines.push(``);
  }

  // ---- upgrades ----
  if (upgrades.length > 0) {
    lines.push(`    // Custom upgrades`);

    const targetNameMap = {
      global_cps: null, click: null,
      cursor: "Cursor", grandma: "Grandma", farm: "Farm", mine: "Mine",
      factory: "Factory", bank: "Bank", temple: "Temple",
      wizardtower: "Wizard Tower", shipment: "Shipment",
      alchemylab: "Alchemy Lab", portal: "Portal",
      timemachine: "Time Machine", antimatter: "Antimatter Condenser",
      prism: "Prism", chancemaker: "Chancemaker",
      fractal: "Fractal Engine", javascript: "Javascript Console",
      idleverse: "Idleverse", cortex: "Cortex Baker",
    };

    upgrades.forEach((u, idx) => {
      const safDesc    = (u.desc || "").replace(/"/g, '\\"');
      const safUpgName = u.name.replace(/"/g, '\\"');

      lines.push(`    Game.customUpgrades["${safUpgName}"] = new Game.Upgrade(`);
      lines.push(`      "${safUpgName}",`);
      lines.push(`      "${safDesc}",`);
      lines.push(`      ${u.cost},`);
      lines.push(`      function() {`);

      if (u.target === "global_cps") {
        lines.push(`        Game.registerHook("cps", function() {`);
        lines.push(`          Game.cookiesPs *= ${u.multiplier};`);
        lines.push(`        });`);
      } else if (u.target === "click") {
        lines.push(`        var _origMC = Game.computedMouseCps;`);
        lines.push(`        Game.computedMouseCps = function() {`);
        lines.push(`          return _origMC.call(this) * ${u.multiplier};`);
        lines.push(`        };`);
      } else {
        const buildingName = targetNameMap[u.target] || u.target;
        lines.push(`        Game.registerHook("cps", function() {`);
        lines.push(`          if (Game.Objects["${buildingName}"]) Game.Objects["${buildingName}"].storedCps *= ${u.multiplier};`);
        lines.push(`        });`);
      }

      lines.push(`      }`);
      lines.push(`    );`);
      lines.push(``);
    });
  }

  // ---- blabs ----
  if (blabs.length > 0) {
    lines.push(`    // Custom blabs (golden cookie flavour messages)`);
    lines.push(`    var ccmmBlabs = [`);
    blabs.forEach((b, i) => {
      const escaped = b.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      lines.push(`      "${escaped}"${i < blabs.length - 1 ? "," : ""}`);
    });
    lines.push(`    ];`);
    lines.push(`    ccmmBlabs.forEach(function(msg) {`);
    lines.push(`      if (Game.goldenCookieBlabMessages && Game.goldenCookieBlabMessages.indexOf(msg) === -1) {`);
    lines.push(`        Game.goldenCookieBlabMessages.push(msg);`);
    lines.push(`      }`);
    lines.push(`    });`);
    lines.push(``);
  }

  // ---- custom JS ----
  if (customJs.trim()) {
    lines.push(`    // Custom code`);
    customJs.split("\n").forEach(l => lines.push(`    ${l}`));
    lines.push(``);
  }

  lines.push(`  } // end init`);
  lines.push(`});`);

  return lines.join("\n");
}

function generateInfoTxt() {
  const modName    = document.getElementById("mod-name")?.value.trim()    || "My Mod";
  const modId      = document.getElementById("mod-id")?.value.trim()      || "my-mod";
  const modVersion = document.getElementById("mod-version")?.value.trim() || "1.0.0";
  const modAuthor  = document.getElementById("mod-author")?.value.trim()  || "";
  const modDesc    = document.getElementById("mod-desc")?.value.trim()    || "";

  const lines = [
    `name:${modName}`,
    `id:${modId}`,
    `version:${modVersion}`,
  ];
  if (modAuthor) lines.push(`author:${modAuthor}`);
  if (modDesc)   lines.push(`description:${modDesc}`);

  return lines.join("\n");
}

function downloadText(filename, text) {
  const blob = new Blob([text], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function exportAndDownload() {
  downloadText("main.js",  generateMod());
  setTimeout(() => {
    downloadText("info.txt", generateInfoTxt());
  }, 150);
}
